name: intro-to-cs
channels:
- anaconda
- conda-forge
dependencies:
- ipykernel=6.22.0
- jupyter=1.0.0
- jupyterlab=3.6.3
- matplotlib=3.7.1
- pandas=2.0.0
- python=3.10.5
- seaborn=0.12.2
- plotly=5.14.0
- scikit-learn=1.2.2
